<a href="https://colab.research.google.com/github/madonnagithub/hello-world/blob/master/Day5_Madonna_Simple_Neural_Network_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [26]:
input_samples=np.array([[1,0,1],[1,1,1],[0,1,0],[0,1,1]])
input_samples

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])

In [27]:
output_samples=np.array([[1],[1],[0],[0]])
output_samples

array([[1],
       [1],
       [0],
       [0]])

In [28]:
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [29]:
sum = np.dot(input_samples,weights)
sum

array([[1.40496888],
       [1.42572083],
       [0.02075195],
       [0.65440018]])

In [0]:
#creating the activation function (sigmoid function)
def activation(x):
  return (1/(1 + np.exp(-x)))

In [31]:
predicted_output=activation(sum)
predicted_output

array([[0.80297119],
       [0.8062337 ],
       [0.5051878 ],
       [0.65800135]])

In [36]:
def gradient(x):
  return x * (1-x)

for i in range(1000):
  sum = 0.02+ np.dot(input_samples,weights)
  predicted_output = activation(sum)
  error = output_samples - predicted_output
  adjustment = error * gradient(predicted_output)
  adjustment
  weights += np.dot(input_samples.T,adjustment)
  weights
error


array([[ 0.00028943],
       [ 0.01527941],
       [-0.01867962],
       [-0.0098602 ]])

In [37]:
predicted_output.round()

array([[1.],
       [1.],
       [0.],
       [0.]])

In [0]:
[]